// client/src/components/NavBar.tsx
import { useEffect, useRef, useState } from "react"
import { Link, useLocation, useNavigate } from "react-router-dom"
import { useAuthStore } from "../stores/auth"
import { useCartStore } from "../stores/cart"
import "../styles/navbar.css"

export default function NavBar() {
  const auth = useAuthStore()
  const cart = useCartStore()
  const location = useLocation()
  const navigate = useNavigate()

  const keywordInputRef = useRef<HTMLInputElement>(null)
  const [keyword, setKeyword] = useState("")
  const [menuOpen, setMenuOpen] = useState(false)
  const userMenuRef = useRef<HTMLDivElement>(null)

  // 路由变化：同步搜索框、关闭菜单
  useEffect(() => {
    if (location.pathname === "/products") {
      setKeyword(
        location.search.includes("keyword=")
          ? new URLSearchParams(location.search).get("keyword") || ""
          : ""
      )
    }
    setMenuOpen(false)
  }, [location])

  // 点击下拉菜单外部或按 Esc 时关闭
  useEffect(() => {
    function onDocClick(e: MouseEvent) {
      if (menuOpen && userMenuRef.current && !userMenuRef.current.contains(e.target as Node)) {
        setMenuOpen(false)
      }
    }
    function onDocKeydown(e: KeyboardEvent) {
      if (e.key === "Escape") setMenuOpen(false)
    }
    document.addEventListener("click", onDocClick)
    document.addEventListener("keydown", onDocKeydown)
    return () => {
      document.removeEventListener("click", onDocClick)
      document.removeEventListener("keydown", onDocKeydown)
    }
  }, [menuOpen])

  function doSearch() {
    const kw = keywordInputRef.current?.value.trim() || ""
    const params = new URLSearchParams(location.search)
    if (kw) params.set("keyword", kw)
    else params.delete("keyword")
    params.set("page", "1")
    navigate(`/products?${params.toString()}`)
  }

  function logout() {
    setMenuOpen(false)
    auth.logout()
    cart.fetchCart()
    navigate("/")
  }

  return (
    <header className="header">
      <div className="container header-inner">
        <Link className="logo" to="/">
          🛍️ 优选商城
        </Link>
        <div className="search-box">
          <input
            ref={keywordInputRef}
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            type="text"
            placeholder="搜索商品..."
            onKeyDown={(e) => e.key === "Enter" && doSearch()}
          />
          <button onClick={doSearch}>🔍</button>
        </div>
        <nav className="nav">
          <Link to="/">首页</Link>
          <Link to="/products">全部商品</Link>
          {auth.isLoggedIn() && <Link to="/orders">我的订单</Link>}
          <button className="cart-btn" onClick={() => navigate("/cart")}>
            🛒 购物车
            {cart.totalQty > 0 && <span className="cart-count">{cart.totalQty}</span>}
          </button>
          {auth.isLoggedIn() ? (
            <div ref={userMenuRef} className="user-menu" onClick={(e) => e.stopPropagation()}>
              <span
                className="user-name"
                role="button"
                tabIndex={0}
                aria-expanded={menuOpen}
                onClick={() => setMenuOpen(!menuOpen)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") setMenuOpen(!menuOpen)
                  if (e.key === "Escape") setMenuOpen(false)
                }}
              >
                👤 {auth.user?.nickname || auth.user?.username} ▾
              </span>
              {menuOpen && (
                <div className="dropdown" onClick={() => setMenuOpen(false)}>
                  <Link to="/profile">个人中心</Link>
                  <Link to="/orders">我的订单</Link>
                  <button onClick={logout}>退出登录</button>
                </div>
              )}
            </div>
          ) : (
            <>
              <Link className="keep" to="/login">
                登录
              </Link>
              <Link className="keep" to="/register">
                注册
              </Link>
            </>
          )}
        </nav>
      </div>
    </header>
  )
}

// client/src/components/NavBar.vue
<template>
  <header class="header">
    <div class="container header-inner">
      <router-link class="logo" to="/">🛍️ 优选商城</router-link>
      <div class="search-box">
        <input v-model="keyword" type="text" placeholder="搜索商品..." @keydown.enter="doSearch" />
        <button @click="doSearch">🔍</button>
      </div>
      <nav class="nav">
        <router-link to="/">首页</router-link>
        <router-link to="/products">全部商品</router-link>
        <router-link v-if="auth.isLoggedIn()" to="/orders">我的订单</router-link>
        <button class="cart-btn" @click="$router.push('/cart')">
          🛒 购物车
          <span v-if="cart.totalQty > 0" class="cart-count">{{ cart.totalQty }}</span>
        </button>
        <template v-if="auth.isLoggedIn()">
          <div ref="userMenuRef" class="user-menu" @click.stop>
            <span
              class="user-name"
              role="button"
              tabindex="0"
              :aria-expanded="menuOpen"
              @click="menuOpen = !menuOpen"
              @keydown.enter="menuOpen = !menuOpen"
              @keydown.esc="menuOpen = false"
            >
              👤 {{ auth.user?.nickname || auth.user?.username }} ▾
            </span>
            <div v-if="menuOpen" class="dropdown" @click="menuOpen = false">
              <router-link to="/profile">个人中心</router-link>
              <router-link to="/orders">我的订单</router-link>
              <button @click="logout">退出登录</button>
            </div>
          </div>
        </template>
        <template v-else>
          <router-link class="keep" to="/login">登录</router-link>
          <router-link class="keep" to="/register">注册</router-link>
        </template>
      </nav>
    </div>
  </header>
</template>

<script setup>
import { onMounted, onUnmounted, ref, watch } from "vue"
import { useRoute, useRouter } from "vue-router"
import { useAuthStore } from "../stores/auth"
import { useCartStore } from "../stores/cart"

const auth = useAuthStore()
const cart = useCartStore()
const route = useRoute()
const router = useRouter()

const keyword = ref("")
const menuOpen = ref(false)
const userMenuRef = ref(null)

watch(
  () => route.query.keyword,
  (kw) => {
    if (route.name === "products") keyword.value = kw || ""
  },
  { immediate: true }
)
watch(
  () => route.fullPath,
  () => {
    menuOpen.value = false
  }
)

// 点击下拉菜单外部或按 Esc 时关闭
function onDocClick(e) {
  if (menuOpen.value && userMenuRef.value && !userMenuRef.value.contains(e.target)) {
    menuOpen.value = false
  }
}
function onDocKeydown(e) {
  if (e.key === "Escape") menuOpen.value = false
}
onMounted(() => {
  document.addEventListener("click", onDocClick)
  document.addEventListener("keydown", onDocKeydown)
})
onUnmounted(() => {
  document.removeEventListener("click", onDocClick)
  document.removeEventListener("keydown", onDocKeydown)
})

function doSearch() {
  const kw = keyword.value.trim()
  router.push({ name: "products", query: { ...route.query, keyword: kw || undefined, page: 1 } })
}

function logout() {
  menuOpen.value = false
  auth.logout()
  cart.fetchCart()
  router.push("/")
}
</script>

<style scoped>
@media (max-width: 600px) {
  .nav a:not(.keep) {
    display: none;
  }
}
</style>
